-- ============================================================
-- 00_db_validation.sql
-- Validation queries for the cleaned SQLite database generated by `01_load_data.ipynb`
--
-- 1. row_count          — total rows in `orders`
-- 2. sample_fields      — sample of Order Date / Ship Date / Postal Code
-- 3. removed_duplicate  — rows for the (Order ID, Product ID) that had a duplicate
-- 4. integrity_summary  — aggregate stats (totals, date range, nulls)
-- 5. repeated_pairs     — (Order ID, Product ID) pairs with more than one line
-- ============================================================

-- 1. row_count
SELECT COUNT(*) AS rows
FROM orders;

-- 2. sample_fields
SELECT "Order Date", "Ship Date", "Postal Code"
FROM orders
LIMIT 3;

-- 3. removed_duplicate
SELECT
    "Row ID",
    "Order ID",
    "Product ID",
    Quantity,
    Sales,
    Discount,
    Profit
FROM orders
WHERE "Order ID" = 'US-2014-150119'
  AND "Product ID" = 'FUR-CH-10002965';

-- 4. integrity_summary
SELECT
    COUNT(*)                                            AS total_rows,
    COUNT(DISTINCT "Row ID")                            AS unique_row_ids,
    SUM(CASE WHEN "Row ID" = 3407 THEN 1 ELSE 0 END)    AS removed_duplicate_present,
    MIN("Order Date")                                   AS min_order_date,
    MAX("Order Date")                                   AS max_order_date,
    SUM(CASE WHEN Sales IS NULL THEN 1 ELSE 0 END)      AS null_sales,
    SUM(CASE WHEN Profit IS NULL THEN 1 ELSE 0 END)     AS null_profit,
    SUM(CASE WHEN Discount IS NULL THEN 1 ELSE 0 END)   AS null_discount
FROM orders;

-- 5. repeated_pairs
SELECT
    "Order ID",
    "Product ID",
    COUNT(*) AS line_count
FROM orders
GROUP BY
    "Order ID",
    "Product ID"
HAVING COUNT(*) > 1
ORDER BY line_count DESC;
